schema_version: 1

context:
  version: 3.2.0
  sha256: 9367ca13d05b0f735daaf7bb75e09b1ff3696e592d2aef16465e8e2856696e04

package:
  name: nvtx-c
  version: ${{ version }}

source:
  url: https://github.com/NVIDIA/NVTX/archive/v${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja

tests:
  - script:
      - if: not win
        then: "test -e \"$PREFIX\"/include/nvtx3/nvToolsExt.h"
      - if: not win
        then: "test -e \"$PREFIX\"/include/nvtx3/nvtx3.hpp"
      - if: win
        then: "if not exist \"%LIBRARY_INC%\"\\nvtx3\\nvToolsExt.h exit 1"
      - if: win
        then: "if not exist \"%LIBRARY_INC%\"\\nvtx3\\nvtx3.hpp exit 1"

about:
  summary: NVIDIA Tools Extension Library (NVTX) C API
  license: Apache-2.0 WITH LLVM-exception
  license_file: LICENSE.txt
  homepage: https://nvidia.github.io/NVTX/

extra:
  recipe-maintainers:
    - conda-forge/cuda
    - shwina
